// AUTO-GENERATED — curated Zolve event data (24 past webinars scraped + planned upcoming CSV).
// Source of truth for the Events page. Past = real Zolve webinars w/ YouTube recordings;
// upcoming = planned sessions (not yet live, shown with a relative date + Register CTA).
// Regenerate from useless-data/events_*.json if the source data changes.

export type EventCategory = 'upcoming' | 'past'
export type EventMedium = 'virtual' | 'in_person'

export interface EventItem {
  id: string
  title: string
  subtitle?: string
  category: EventCategory
  medium: EventMedium
  /** Human-readable date as authored (e.g. "Jun 27" or "13th June'25, 6:30 PM IST Friday") */
  dateText: string
  /** ISO date for upcoming events (used for sorting + "Event in N days") */
  dateISO?: string
  speakerName?: string
  speakerDesignation?: string
  speakerPhoto?: string
  youtubeUrl?: string
  thumbnail?: string
  tags: string[]
  registrationPlatform?: string
}

export const upcomingEvents: EventItem[] = [
  {"id":"up-2026-06-27-cracking-the-f1-interview-india-consulat","title":"Cracking the F1 Interview - India Consulates (Chennai, Delhi, Hyderabad, Mumbai)","category":"upcoming","medium":"virtual","dateText":"Jun 27","dateISO":"2026-06-27","tags":["Interview Prep"]} as EventItem,
  {"id":"up-2026-06-27-f1-visa-success-rest-of-world-edition-ni","title":"F1 Visa Success - Rest of World Edition (Nigeria, Nepal, Bangladesh, Philippines)","category":"upcoming","medium":"virtual","dateText":"Jun 27","dateISO":"2026-06-27","tags":["F-1 Visa"]} as EventItem,
  {"id":"up-2026-06-27-f1-visa-ama-row-open-session-myths-buste","title":"F1 Visa AMA - RoW Open Session (Myths busted, reapplicants welcome)","category":"upcoming","medium":"virtual","dateText":"Jun 27","dateISO":"2026-06-27","tags":["Rejections"]} as EventItem,
  {"id":"up-2026-07-04-d-s-ending-september-2026-what-every-f1-","title":"D/S Ending September 2026 - What Every F1 Student Must Do Now","category":"upcoming","medium":"virtual","dateText":"Jul 4","dateISO":"2026-07-04","tags":["Status / OPT"],"registrationPlatform":"BookMyVisa Slot"} as EventItem,
  {"id":"up-2026-07-18-uk-graduate-route-visa-2026-indian-stude","title":"UK Graduate Route Visa 2026 - Indian Student Playbook (Post-study work, Skilled Worker transition)","category":"upcoming","medium":"virtual","dateText":"Jul 18","dateISO":"2026-07-18","tags":["UK Visa"],"registrationPlatform":"Visa Folder"} as EventItem,
  {"id":"up-2026-07-24-your-first-30-days-in-the-us-banking-ssn","title":"Your First 30 Days in the US - Banking, SSN, Credit, Housing","category":"upcoming","medium":"virtual","dateText":"Jul 24","dateISO":"2026-07-24","tags":["Life in US"]} as EventItem,
  {"id":"up-2026-08-21-surviving-your-first-semester-money-ment","title":"Surviving Your First Semester - Money, Mental Health & Community for Indian Students in the US","category":"upcoming","medium":"virtual","dateText":"Aug 21","dateISO":"2026-08-21","tags":["Life in US"]} as EventItem,
]

export const pastEvents: EventItem[] = [
  {"id":"spring2026webinar2","title":"Spring 2026 F-1 Visa Update","subtitle":"Latest Interview Trends & Immigration Experiences","category":"past","medium":"virtual","dateText":"17th Dec (Wednesday), 5 PM IST","speakerName":"shachi","speakerDesignation":"Visa Expert","speakerPhoto":"https://static.zolve.com/images/sachi.png","youtubeUrl":"https://youtu.be/oH-LFMDjIDs?si=AAjNR8VielXTfCB8","thumbnail":"https://img.youtube.com/vi/oH-LFMDjIDs/hqdefault.jpg","tags":["F-1 Visa"]} as EventItem,
  {"id":"visa-webinar-13-June-25-past","title":"What Visa Officers Look for in Your Answers","subtitle":"F1 Visa Interview Tips","category":"past","medium":"virtual","dateText":"13th June'25, 6:30 PM IST Friday","speakerName":"Charity B.","speakerDesignation":"Former U.S Consular Officer, Udeti Visa","youtubeUrl":"https://youtu.be/wZ7jS7aad98","thumbnail":"https://img.youtube.com/vi/wZ7jS7aad98/hqdefault.jpg","tags":["Interview Prep"]} as EventItem,
  {"id":"visa-webinar-06-June-25_past1","title":"What to Say and What to Avoid during F1 Visa interview","subtitle":"QnA with Visa Expert","category":"past","medium":"virtual","dateText":"6th June'25, 5:30 PM IST Friday","speakerName":"Shachi Mall","speakerDesignation":"Visa Expert, 100k YT subscribers","speakerPhoto":"https://static.zolve.com/images/sachi.png","youtubeUrl":"https://youtu.be/sLttNfxhIBY?si=UhZC7uAJ1Crcdgk5","thumbnail":"https://img.youtube.com/vi/sLttNfxhIBY/hqdefault.jpg","tags":["Interview Prep"]} as EventItem,
  {"id":"visa-webinar-30-May-25","title":"Social Media Screening & Visa Success","subtitle":"What Students Must Know","category":"past","medium":"virtual","dateText":"30th May'25, 12 PM IST Friday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/EfmHxW2BReI","thumbnail":"https://img.youtube.com/vi/EfmHxW2BReI/hqdefault.jpg","tags":["F-1 Visa"]} as EventItem,
  {"id":"visa-webinar-17-May-25-past","title":"Get Your F1 Visa Approved in 30 Seconds","subtitle":"Your guide to a flawless F1 visa interview.","category":"past","medium":"virtual","dateText":"17th May'25, 12 PM IST Saturday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/1u2ySdhFFN4?si=hatShljmJ00ZLooP","thumbnail":"https://img.youtube.com/vi/1u2ySdhFFN4/hqdefault.jpg","tags":["F-1 Visa"]} as EventItem,
  {"id":"visa-webinar-09-May-25","title":"Turn Refusals into Approvals","subtitle":"Stay Focused & Prep Better for Your Visa Interview","category":"past","medium":"virtual","dateText":"9th May'25, 5:30 PM IST Friday","speakerName":"Caroline A.","speakerDesignation":"Retired U.S Consular Officer, Udeti Visa","youtubeUrl":"https://youtu.be/rUV0LlsS8ZU?si=o9IQVgwj3swsLfYG","thumbnail":"https://img.youtube.com/vi/rUV0LlsS8ZU/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa-webinar-25-Apr-25","title":"F1 Visa Scams. Rejections. Confusion.","subtitle":"Let’s put a full stop to it.","category":"past","medium":"virtual","dateText":"25th April'25, 5:30 PM IST, Friday","speakerName":"Yvette Bansal","speakerDesignation":"Former Consular Officer","youtubeUrl":"https://youtu.be/KVsQDq8ZL_c?si=i8OdaVgNmegqSujc","thumbnail":"https://img.youtube.com/vi/KVsQDq8ZL_c/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa_webinar_21dec_past","title":"F1 Visa Mock Interview","subtitle":"Training with Visa Coach","category":"past","medium":"virtual","dateText":"21st Dec'24, 12 PM IST Saturday","speakerName":"Shachi Mall","speakerDesignation":"Visa Coach","speakerPhoto":"https://static.zolve.com/images/sachi.png","youtubeUrl":"https://youtu.be/jFZolJtRr2Q?si=eIAOZL3r7IoImR6N","thumbnail":"https://img.youtube.com/vi/jFZolJtRr2Q/hqdefault.jpg","tags":["Mock Interview"]} as EventItem,
  {"id":"visa_webinar_20nov","title":"Step-by-Step DS-160 Form Filling Guide","subtitle":"with a Visa Expert","category":"past","medium":"virtual","dateText":"20th Nov'24, 5 PM IST","speakerName":"Brian Taylor","speakerDesignation":"Visa Expert, Interviewbuddy","speakerPhoto":"https://static.zolve.com/images/png/brain-taylor.png","youtubeUrl":"https://youtu.be/XZlk64z3JmA?si=M59mszF4XcI1uFqH","thumbnail":"https://img.youtube.com/vi/XZlk64z3JmA/hqdefault.jpg","tags":["DS-160"]} as EventItem,
  {"id":"visa_webinar_18dec_past","title":"F-1 Visa Rejected? Here's What to Do Next!","subtitle":"Learn from Ex-Visa Officer","category":"past","medium":"virtual","dateText":"18th Dec'24, 5 PM IST Wednesday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/EiA1jguwKjA","thumbnail":"https://img.youtube.com/vi/EiA1jguwKjA/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa_webinar_06dec_past","title":"F-1 Visa Mock Interview","subtitle":"With Senior","category":"past","medium":"virtual","dateText":"6th Dec'24, Friday 5 PM IST","speakerName":"Sri Charan Ravva","speakerDesignation":"Central Michigan University","speakerPhoto":"https://static.zolve.com/images/png/sri-charan.png","youtubeUrl":"https://youtu.be/Y3vjbvojgUk","thumbnail":"https://img.youtube.com/vi/Y3vjbvojgUk/hqdefault.jpg","tags":["Mock Interview"]} as EventItem,
  {"id":"visa_webinar_29nov-past","title":"Busting Myths About the US F1 Visa Process","subtitle":"with Q&A","category":"past","medium":"virtual","dateText":"29th Nov'24, 5 PM IST","speakerName":"Sanjay Kaushik","speakerDesignation":"Ex-Visa Officer, US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/DyfoyVcUtw0?si=4rzib95g03zShAFH","thumbnail":"https://img.youtube.com/vi/DyfoyVcUtw0/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa_webinar_22nov_past","title":"F-1 Visa Mock Interview","subtitle":"With Ex-visa Officer","category":"past","medium":"virtual","dateText":"22nd Nov'24, Friday 5 PM IST","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/r1sCm2vHMjg?si=AuFXSpRQNjZBQgWM","thumbnail":"https://img.youtube.com/vi/r1sCm2vHMjg/hqdefault.jpg","tags":["Mock Interview"]} as EventItem,
  {"id":"visa-webinar-06-July-24","title":"USA F1 Visa Mock Interview","subtitle":"For Fall 2024 Students","category":"past","medium":"virtual","dateText":"6th July'24, 12 PM IST Saturday","speakerName":"Shachi Mall","speakerDesignation":"Travel & Visa Coach, YT Subscribers- 83.2k","speakerPhoto":"https://static.zolve.com/images/sachi.png","youtubeUrl":"https://youtu.be/QrbbRD8SAWs","thumbnail":"https://img.youtube.com/vi/QrbbRD8SAWs/hqdefault.jpg","tags":["Mock Interview"]} as EventItem,
  {"id":"visa-webinar-28-June-24","title":"F1 Mock Visa interview","subtitle":"With Ex-Visa officer","category":"past","medium":"virtual","dateText":"28th June'24, 5 PM IST Friday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy, New Delhi","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/g2EPqdGdnpo?si=ZOYUOysKoGWyax10","thumbnail":"https://img.youtube.com/vi/g2EPqdGdnpo/hqdefault.jpg","tags":["Interview Prep"]} as EventItem,
  {"id":"visa-webinar-19-June-24","title":"Understanding F1 Visa Approvals","subtitle":"Delhi Consulate vs. Mumbai Consulate","category":"past","medium":"virtual","dateText":"19th June'24, 12 PM IST Wednesday","youtubeUrl":"https://www.youtube.com/live/2Arji9szoH8?si=EQdgP_PFHEhUZLht","thumbnail":"https://img.youtube.com/vi/2Arji9szoH8/hqdefault.jpg","tags":["F-1 Visa"]} as EventItem,
  {"id":"visa-webinar-09-June-24","title":"F1 Visa Mock Interview","subtitle":"Training with VISA Officer","category":"past","medium":"virtual","dateText":"9th June'24, 12 PM IST Sunday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy, New Delhi","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://youtu.be/Ak80nOLjErM?si=cE-cER49yux5KljH","thumbnail":"https://img.youtube.com/vi/Ak80nOLjErM/hqdefault.jpg","tags":["Mock Interview"]} as EventItem,
  {"id":"visa-webinar-01-june-24","title":"Things to know before moving to USA","subtitle":"AMA with Sanjeev (Telugu)","category":"past","medium":"virtual","dateText":"1st June'24, 12 PM IST Saturday","speakerName":"Sanjeev Sriram","speakerDesignation":"YouTube Subscribers- 108k","speakerPhoto":"https://static.zolve.com/images/SanjeevV2.png","youtubeUrl":"https://youtu.be/gim-BrOik_I","thumbnail":"https://img.youtube.com/vi/gim-BrOik_I/hqdefault.jpg","tags":["Life in US"]} as EventItem,
  {"id":"visa-webinar-21-Apr-24","title":"US F1 Visa","subtitle":"Slots Update, Portal Changes & DS-160","category":"past","medium":"virtual","dateText":"21st April' 24, 2 PM IST Sunday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://www.youtube.com/live/ju7BAuKczVc?si=4QHXvde1R1-V5_qR","thumbnail":"https://img.youtube.com/vi/ju7BAuKczVc/hqdefault.jpg","tags":["F-1 Visa"]} as EventItem,
  {"id":"visa-webinar-view-7-Apr-24","title":"Busting Myths About the US F1 Visa Process","subtitle":"Q&A Session with Visa Expert","category":"past","medium":"virtual","dateText":"7th April' 24, 2 PM IST Sunday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://www.youtube.com/watch?v=DQ2Qki8tErQ","thumbnail":"https://img.youtube.com/vi/DQ2Qki8tErQ/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa-webinar-4-may-24","title":"Common Mistakes in DS-160","subtitle":"Major Reasons for Rejections","category":"past","medium":"virtual","dateText":"4th May'24, 2 PM IST Saturday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://www.youtube.com/live/3ApH-5JIZ2g?si=4jYwdMh-rg9pgGpF","thumbnail":"https://img.youtube.com/vi/3ApH-5JIZ2g/hqdefault.jpg","tags":["DS-160"]} as EventItem,
  {"id":"visa-webinar-18-may-24","title":"F1 VISA REJECTION?","subtitle":"Financial Documents, Common Mistakes, and How to Avoid Them","category":"past","medium":"virtual","dateText":"18th May'24, 1 PM IST Saturday","speakerName":"Sanjay Kaushik","speakerDesignation":"Former Visa Specialist at US Embassy","speakerPhoto":"https://static.zolve.com/images/png/sanjay-kaushik-profile.png","youtubeUrl":"https://www.youtube.com/live/LN8_NV1zaWk?si=bgcn8XzWYA6uYrWw","thumbnail":"https://img.youtube.com/vi/LN8_NV1zaWk/hqdefault.jpg","tags":["Rejections"]} as EventItem,
  {"id":"visa-webinar-25-may-24","title":"How I Cracked My Visa Interview (Telugu)","subtitle":"AMA with Neelesh","category":"past","medium":"virtual","dateText":"25th May'24, 12 PM IST Saturday","speakerName":"Neelesh Alapathi","speakerDesignation":"YouTube subscribers- 105k","speakerPhoto":"https://static.zolve.com/images/png/Neelesh%20Alapati.jpeg","youtubeUrl":"https://www.youtube.com/live/wniZKrjC848?si=0FFh-uw5Z6IdeQtv","thumbnail":"https://img.youtube.com/vi/wniZKrjC848/hqdefault.jpg","tags":["Interview Prep"]} as EventItem,
  {"id":"visa-webinar-29-may-24","title":"How to structure your answers for F1 Visa interview","subtitle":"AMA with Sachi","category":"past","medium":"virtual","dateText":"29th May'24, 1 PM IST Wednesday","speakerName":"Shachi Mall","speakerDesignation":"Travel & Visa Coach, YouTube Subscribers- 83.2k","speakerPhoto":"https://static.zolve.com/images/sachi.png","youtubeUrl":"https://www.youtube.com/live/Rp_Yn48nXA4?si=dkgMK5sV_AjBUXT_","thumbnail":"https://img.youtube.com/vi/Rp_Yn48nXA4/hqdefault.jpg","tags":["Interview Prep"]} as EventItem,
]

export const allEvents: EventItem[] = [...upcomingEvents, ...pastEvents]
